### ISSUE TITLE
OpenID Connect Client ID and Secret Storage

### ISSUE THREAD

**Issue by jim0020** [oracle/cordova-plugin-oracle-idm-auth#1]
When using this plugin to authenticate via OpenID Connect, you need to have the Client ID and Client Secret accessible to pass to the plugin API.  How does one keep those secure in a Cordova application?  What's the best practice here?  It seems like there is no good way to keep the Client ID and Secret secret.

Thanks!

**Comment by anandvnath** [comment]
AFAIK clientId and clientSecret are part of the auth config. These are expected when the flow is initialized. After this, the user has to login anyway. 

What is the concern in having this part of the app JS code? How does it become a security issue and why does it need to be secured in cordova?

**Comment by anandvnath** [comment]
After few discussions with security experts team, looks like the client secret is an issue after all. They recommended using public mobile client app which does not have the secret for mobile usecases.
