### ISSUE TITLE
Error message 50201 not defined

### ISSUE THREAD

**Issue by fangornoftheforest** [oracle/cordova-plugin-oracle-idm-auth#12]
Using the following code to build an OIDC request:

                var authProperties = cordova.plugins.IdmAuthFlows.newOpenIDConnectPropertiesBuilder(
                    'com.foo',
                    'OAuthAuthorizationCode',
                    'https://login.microsoftonline.com/<<tenantid>>/discovery/v2.0/keys',
                    <<clientid>>
                )   .oAuthClientSecret('clientsecret') <- added this even though this should not be present in Auth Code Flow
                    .logoutTimeOutInSeconds(60)
                    .browserMode(cordova.plugins.IdmAuthFlows.BrowserMode.External)
                    .oAuthRedirectEndpoint(<<redirectUrl>>) <- this is a universal link
                    .oAuthAuthorizationEndpoint(<<authorization endpoint>>)
                    .oAuthScope(['api://foo.Read', 'openid', 'offline_access', 'email'])
                    .put('prompt', 'login')
                    .enablePKCE(true)
                    .build();

This is the response at authflow.login()

Uncaught (in promise):
    errorCode: "50201"
    errorSource: "plugin"
    translatedErrorMessage: ""

**Comment by manish2788** [comment]
@fangornoftheforest Can you replace the deprecated API in your code and then verify
Doc Reference : https://oracle.github.io/cordova-plugin-oracle-idm-auth/global.html#newOpenIDConnectPropertiesBuilder

**Comment by fangornoftheforest** [comment]
@manish2788 Thanks, flow continues when not using deprecated builder
