### ISSUE TITLE
iOS NSInvalidArgumentException 'The specified URL has an unsupported scheme'

### ISSUE THREAD

**Issue by fangornoftheforest** [oracle/cordova-plugin-oracle-idm-auth#13]
Callback to application is unsuccessful due to the scheme being null.

"The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported."

The logging on didReceiveAuthenticationChallenge is: 

{
    frontChannelResponse = "<null>";
    frontChannelURL = "(null)?client_id=foo&response_type=code&code_challenge=bar&etc"
}

How does this plugin define the scheme?

**Comment by manish2788** [comment]
@fangornoftheforest Can you provide more detail of your implementation? Which URL scheme are you using and which APIs you are using from plugin to configure the authentication.

**Comment by manish2788** [comment]
Closing the issue due to lack of response.
