### ISSUE TITLE
How to use SAML authentication?

### ISSUE THREAD

**Issue by hvhaaren** [oracle/cordova-plugin-oracle-idm-auth#5]
I's trying to use this plugin for a SAML server configuration and it's not clear for me how to setup the client plugin. In the the FAQ it says to use the newFedAuthPropertiesBuilder for this and I do this and I see it doing a GET for the login URL. 

I'm not an SAML expert but what I understand now is the KeyCloak Identity Provider expects a POST login request with a SAML message in the body that specifies the identity that wants to logon. How can we send this data with the plugin?

Any help will be appreciated. Thanks.

**Comment by anandvnath** [comment]
Assuming that you have a working SAML Identity Provider (IDP) setup, the configuration needed in the plugin is to create a newFedAuthPropertiesBuilder and provide loginUrl, logoutUrl, loginSuccessUrl and loginFailureUrl. 

loginSuccessUrl is typically a light weight protected page which can be access only after successful authentication. In some cases this can be loginUrl itself. This depends on your server configuration.

loginFailureUrl is the page loaded in case of authentication failure. For e.g, when user is not able to provide correct credentials, IDP may have a policy to prevent user from trying to login any further (say based on max retry attempts) and then redirected back with error code. This is again dependent on server configuration.

What the plugin does is to load loginUrl on a webView. Plugin then waits until the loginSuccessUrl or loginFailureUrl is loaded on the webview. POST requests that you mention are internal to the IDP and Service Provider (SP) and not something the plugin is involved with. 

Hope this helps.

**Comment by hvhaaren** [comment]
Thanks, it's clear now, the loginUrl should go to the service provider and that will redirect to the Identity provider and do the saml stuff. The plug just awaits the result of this whole login procedure. 

Thanks for the help.
