### ISSUE TITLE
isAuthenticated() returning false when not logged out

### ISSUE THREAD

**Issue by BmsVisionJo** [oracle/cordova-plugin-oracle-idm-auth#6]
I am currently having some issues trying to handle the logout when there is no connection to the network.
The authflow logout function throws an error like I would expect but I would like to be able to keep trying when connection restores.

However if a first attempt to logout gives an error, the next time isAuthenticated() is called, it returns false wich I would assume means successfull logout.
And if I force the logout function to execute again it does not fail anymore and also seems successfull.

Is there a way to solve this issue because if logout fails but passes the code it shows my login again and immediately logs in the last authenticated user because I assume the cookie is still there.

Why is the error not thrown each time?

```  if (this._authFlow) {
            this._authFlow.isAuthenticated()
                .then((authenticated: boolean) => {
                    if (authenticated || this._failedToLogout) {
                        var logoutPromise = this._authFlow.logout()
                            .then((resp: any) => {
                                this._accessTokenReceived.next(false);
                                this._localStorageService.authenticated = false;
                                this._failedToLogout = false;
                            })
                            .catch((err: any) => {
                                console.error("Logout failed with error: " + err);
                                this._failedToLogout = true;
                            });
                    }

**Comment by anandvnath** [comment]
The behavior is that plugin logs out the user even if there was an error during logout. This is documented in here: https://oracle.github.io/cordova-plugin-oracle-idm-auth/RemoteAuthenticationFlow.html#logout

>> Is there a way to solve this issue because if logout fails but passes the code it shows my login again and immediately logs in the last authenticated user because I assume the cookie is still there.

What kind of auth flow are you using? I think the plugin clears the cookies at the backend. Do you see the behavior really happening?
