### ISSUE TITLE
How to get the Access Token with an Authorization Flow.

### ISSUE THREAD

**Issue by jim0020** [oracle/cordova-plugin-oracle-idm-auth#7]

**Comment by jim0020** [comment]
I have code to successfully log in to my OpenIDConnect service.  I have received an authorization code via the callback custom URL.  How do I get the ID/Access Token to authenticate with my web application (which is not the OIDC service server)?

**Comment by anandvnath** [comment]
If you create an [OpenID flow](https://oracle.github.io/cordova-plugin-oracle-idm-auth/OpenIDConnectPropertiesBuilder.html), then the plugin takes care of the entire login flow, including exchanging AZCode for Access token. Post that, the access token can be obtained using [getHeaders](https://oracle.github.io/cordova-plugin-oracle-idm-auth/RemoteAuthenticationFlow.html#getHeaders) API for accessing secured resource.

**Comment by jim0020** [comment]
@anandvnath Thanks, that's the answer I was expecting and makes sense.  

1) However, in my login() callback, when iterating through getHeaders, it seems to be empty.  Therefore there's no access token.  Which is what is causing my confusion.  Correction: the callback provided to flow.getHeaders() never gets called.

2) My handleOpenUrl() function is being called using my redirect URL.  The code parameter in the URL, is this the auth code or the actual access token?

**Comment by jim0020** [comment]
Looks like I was setting up the getHeaders() call incorrectly.  So you can ignore #1 in the previous comment.

**Comment by jim0020** [comment]
authFlow.getHeaders() returns the Authorization Token, something like "Bearer ABCDEFG...".  But how do I get the ID Token JWT? Or the user profile info in the decoded ID Token?  The OMOIDCAuthenticationService is holding the user profile info, but I can't figure out how to access it from the javascript side.

**Comment by anandvnath** [comment]
Answered in https://github.com/oracle/cordova-plugin-oracle-idm-auth/issues/9
