### ISSUE TITLE
How do you access the Open ID Connect user profile information stored in the ID Token?

### ISSUE THREAD

**Issue by jim0020** [oracle/cordova-plugin-oracle-idm-auth#9]
I have successfully authenticated using Open ID Connect.  How do you access the user profile information that was received via the ID Token?  Or how do you access the ID Token itself?  The RemoteAuthenticationFlow object doesn't seem to hold this info.  And its getHeaders() method only returns the Access Token.  In the iOS debugger I can see the user profile information in OMOIDCAuthenticationService at line 38.  So the information is present, but how do you access it from the javascript side?

**Comment by anandvnath** [comment]
ID Token is not exposed as of now. Userinfo can be obtained by hitting the userinfo end point. Typically this is part of OpenID discovery URL of format https://server/oauth2/v1/userinfo
